### PR TITLE
Implements convert methods exportObj + exportDae

### PR DESCRIPTION
**Pull request by bnjm**
Drawbacks: Is not opinionated about which texture keys get sent to the processing server, lets the processing server which decide which to use and send back

### CODE REVIEW

**Comment by tomas-polach** [comment]
@Aadjou i couldn't find your comment in the code but @bnjm told me about your proposal of moving whenDon() to utils namespace during a code review and i fully agree

**Comment by Aadjou** [comment]
you can see the comments if you click on "files changed" :)

**Comment by bnjm** [comment]
Also forgot to mention this includes a breaking change for anyone who was using `io3d.light.bake.whenDone`... is now `io3d.utils.processing.whenDone`

**Comment by Aadjou** [comment]
we're in beta and i'm not sure if it is publicly used yet, please make sure you include it in the pull request 
please also look at the guidlines for pull requests https://github.com/archilogic-com/devops/blob/master/docs/development/pull-request.md

**Comment by tomas-polach** [comment]
@Aadjou good point!

baking is not being publicly used and it should be in a separate branch in fact. sorry, my bad. will use separate branch next time.

**Comment by tomas-polach** [comment]
@Aadjou sorry i don't get it: can't find your comments... this is how "files changed" looks  to me:
implements_convert_methods_exportobj___exportdae_by_bnjm_ _pull_request__75_ _archilogic-com_3dio-js
implements_convert_methods_exportobj___exportdae_by_bnjm_ _pull_request__75_ _archilogic-com_3dio-js
implements_convert_methods_exportobj___exportdae_by_bnjm_ _pull_request__75_ _archilogic-com_3dio-js
implements_convert_methods_exportobj___exportdae_by_bnjm_ _pull_request__75_ _archilogic-com_3dio-js_and_localhost_8081_examples_furniture-library_html_and_google-blocks_html_-_3dio-inspector-plugins_-____repos_a_3dio-inspector-plugins_
implements_convert_methods_exportobj___exportdae_by_bnjm_ _pull_request__75_ _archilogic-com_3dio-js

**Pull request merged**
