### PR TITLE
fix tour for aframe >= 0.8.0

### PR DESCRIPTION
**Pull request by BoryaMogila**
**Scope & Features**
- aframe-animation-component does not work with aframe > = 0.8.0, because aframe has changed api to rotate the camera. I rewrote the tour component using animejs directly.

**Design**
- Design has not changed

**How to use**
- Change aframe-animation-component script to animejs script

**Notes**
- I change tour example for test new functionality

### CODE REVIEW

**Comment by tomas-polach** [comment]
Thx!! I will have a look later today

**Comment by BoryaMogila** [comment]
Ok

**Comment by tomas-polach** [comment]
Looks good!

Only consideration: In combination with A-Frame 0.7 (tested with example-browsers/tour/index.html) it looks like the camera doesn't focus on the tour-waypoints correctly. Do you think you can fix that? If not, we could bump the 3dio.js version number to 2.0 - which would be the official version number supporting A-Frame 0.8. (Keeping 3dio.js 1.x for A-Frame 0.7 suport)

**Comment by BoryaMogila** [comment]
I fix bug with 0.7.0 support. Now must work fine.

**Comment by tomas-polach** [comment]
Cool thx. Will test again. (Don't worry about the merge conflict. It's just the build files)

**Comment by tomas-polach** [comment]
Works correctly! Great! I will merge it and do a release on Thursday.

**Comment by tomas-polach** [comment]
One more change request: In order to not break earlier implementations using `aframe-animation-component.js`, could you please add this to `component/tour.js`:
```js
var anime = window.anime || AFRAME.anime
```
and then use `anime` instead of `window.anime` here:
- https://github.com/BoryaMogila/3dio-js/blob/fixTour/src/aframe/component/tour.js#L149
- https://github.com/BoryaMogila/3dio-js/blob/fixTour/src/aframe/component/tour.js#L158
- https://github.com/BoryaMogila/3dio-js/blob/fixTour/src/aframe/component/tour.js#L165

**Comment by BoryaMogila** [comment]
I add it. But its work only for aframe-animation-component >= 4.0.0

**Comment by BoryaMogila** [comment]
ok

**Comment by BoryaMogila** [comment]
I add some fixes for older aframe versions after test on real plan. [link for test plan](https://seemly-canid.glitch.me/).

**Review by tomas-polach — APPROVED** [review]

**Comment by tomas-polach** [comment]
@BoryaMogila I did merge your changes and did a release with version number 2.0.0. I will update the docs accordingly later today. Pls. let me know if everything works as expected in your use case.

PS: I've set easing to `easeInOutSine` instead of `linear` because that was also the default in earlier 3dio.js versions.

Thanks again for your contribution :)

**Comment by BoryaMogila** [comment]
Hi. All works fine. I update test exemple

чт, 2 серп. 2018, 15:08 користувач Tomas Polach <notifications@github.com>
пише:

**Pull request merged**
